const excuses = {
    absurdas: [
        "Fui abduzido por alienígenas e só me devolveram agora.",
        "Tropecei numa viagem no tempo e só voltei agora.",
        "Um esquilo roubou minhas chaves e tive que negociar com ele.",
        "Fui engolido por um sofá e só consegui sair agora.",
        "Meu espelho começou a discutir comigo e perdi a hora.",
        "Um duende sequestrou meu relógio.",
        "O Wi-Fi da minha casa decidiu tirar férias.",
        "Fui teletransportado sem querer para outra dimensão.",
        "Um gato desconhecido me desafiou para um duelo de olhares.",
        "Um corvo me entregou uma carta misteriosa e precisei investigar.",
        "Minha casa foi invadida por pinguins e precisei negociar com eles.",
        "Meu despertador foi possuído por um espírito brincalhão.",
        "A gravidade parou de funcionar na minha casa por um tempo.",
        "Me transformei em um NPC e fiquei preso em um loop.",
        "Meu clone do futuro apareceu e precisei ouvir seus conselhos.",
        "O Google Maps me fez dar a volta ao mundo antes de chegar aqui.",
        "Eu escorreguei e caí em um buraco interdimensional.",
        "A Lua me hipnotizou e só acordei agora.",
        "Meu guarda-roupa virou um portal e precisei explorar.",
        "O controle remoto do tempo ficou travado no modo “soneca”.",
        "O metrô decidiu brincar de esconde-esconde comigo.",
        "Um robô do futuro tentou me convencer a salvar o mundo.",
        "Meu cachorro decidiu que hoje era o dia do apocalipse caseiro.",
        "Uma coruja apareceu na minha janela com uma missão secreta.",
        "Meu carro virou um Transformer e me levou para outra cidade.",
        "Um tornado de folhas me carregou para longe.",
        "Precisei fugir de um esquilo ninja no caminho.",
        "Um mago apareceu e me transformou temporariamente em um sapo.",
        "Fui desafiado para uma batalha de dança por um espírito ancestral.",
        "Meu celular foi engolido pelo sofá e só achei agora.",
        "Tive que resolver um enigma para conseguir sair de casa.",
        "Fui confundido com uma celebridade e sequestrado por fãs.",
        "Um furacão de borboletas bloqueou minha saída.",
        "Tive que convencer um pombo a devolver meu café da manhã.",
        "O elevador decidiu virar um parque de diversões hoje.",
        "Meu reflexo começou a agir de forma independente.",
        "O tempo andou para trás e precisei reviver meu dia todo.",
        "Um mago me colocou em uma quest de RPG sem minha permissão.",
        "O Wi-Fi da minha casa criou consciência e se recusou a funcionar.",
        "Meu carro virou um barco e precisei navegar até aqui.",
        "Um samurai fantasma me desafiou para um duelo antes de sair de casa.",
        "Uma pizza voadora bloqueou minha porta.",
        "Fui abduzido por um grupo de formigas cientistas.",
        "O sol piscou para mim e perdi a noção do tempo.",
        "Meu micro-ondas virou um portal do tempo.",
        "Tive que negociar com uma gangue de gatos pelo meu caminho.",
        "Meu guarda-chuva começou a flutuar e fui junto.",
        "O despertador fez um motim e se recusou a tocar.",
        "Uma fada apareceu e me fez perder a noção da realidade.",
        "Meu cacto começou a andar e precisei segui-lo.",
        "A porta da minha casa virou um quebra-cabeça.",
        "Meu espelho decidiu me trollar e só percebi agora.",
        "Um peixe falante pediu minha ajuda para salvar o oceano."
    ],
    aleatorias: [
        "O Wi-Fi caiu e um pombo levou meu celular.",
        "Meu cachorro escondeu minha carteira e só achei agora.",
        "Fiquei preso no elevador com um entregador de pizza.",
        "O espelho me desafiou para um duelo de olhares.",
        "Meu chinelo quebrou no meio da rua e tive que improvisar.",
        "A porta de casa decidiu que eu não podia sair hoje.",
        "Meu gato escondeu meu carregador e precisei achá-lo primeiro.",
        "Meu carro engasgou e precisei dar água para ele.",
        "O ônibus fez um tour turístico antes de chegar no ponto certo.",
        "Meu relógio atrasou uma hora só para me trollar.",
        "Fui desafiado para um duelo de polegares no mercado.",
        "Minha geladeira congelou meu café e precisei descongelar.",
        "Um pombo bloqueou meu caminho e fiquei preso.",
        "Meu travesseiro não quis me soltar de manhã.",
        "O controle remoto sumiu e precisei procurar antes de sair.",
        "Tentei sair de casa, mas a gravidade estava mais forte hoje.",
        "O universo me deu um 'erro 404' ao acordar.",
        "Esqueci como andar por alguns minutos e precisei reaprender.",
        "Meu Wi-Fi pediu folga e se recusou a funcionar.",
        "O trânsito estava tão lento que consegui fazer amizade com o motorista do lado.",
        "Meu relógio parou e só voltou a funcionar quando já era tarde.",
        "Um cachorro aleatório me adotou e precisei resolver isso antes de sair.",
        "Meu celular entrou no modo 'não perturbe' e não me avisou.",
        "O alarme tocou no modo silencioso.",
        "Meu gato bloqueou a tela do celular.",
        "O despertador decidiu me ignorar hoje.",
        "Esqueci meu nome e precisei lembrar antes de sair.",
        "Fui contratado como figurante de um filme sem querer.",
        "O sorvete derreteu e precisei salvar o chão.",
        "A caneta da minha casa sumiu e passei a manhã procurando.",
        "Meu reflexo começou a agir diferente e me assustei.",
        "Um gato aleatório me seguiu e precisei levá-lo para casa.",
        "O elevador só parava no andar errado.",
        "Meu cachorro decidiu que eu não ia trabalhar hoje.",
        "A Lua estava bonita demais e perdi a noção do tempo.",
        "Fui convidado para um casamento de desconhecidos e não pude recusar.",
        "Meu carro resolveu testar o modo 'não ligar'.",
        "O Wi-Fi caiu e eu também.",
        "O micro-ondas explodiu pipoca por toda a cozinha.",
        "Um passarinho pousou na minha janela e começamos uma conversa séria.",
        "Descobri que meu relógio estava no fuso horário errado.",
        "Um esquilo pegou minha chave e tive que negociar.",
        "O ônibus decidiu que hoje não era dia de parar no meu ponto.",
        "A luz piscou e achei que era um código secreto.",
        "Meu vizinho me prendeu numa conversa sobre jardinagem.",
        "Perdi a senha do meu carro e precisei redefinir.",
        "Meu ventilador prendeu meu cabelo e precisei resgatar.",
        "Meu café decidiu que minha roupa precisava de uma nova estampa.",
        "Descobri que meu GPS me levou para outro estado.",
        "Meu despertador falhou e achei que ainda era madrugada.",
        "Minha bicicleta decidiu que não queria mais funcionar.",
        "O trânsito estava tão parado que comecei a ler um livro.",
        "Um corvo tentou me convencer a me tornar seu aprendiz."
    ],
    namoro: [
        "Eu ia te chamar, mas meu celular reiniciou e esqueci.",
        "Estava tão nervoso que acabei dormindo sem querer.",
        "Meu horóscopo disse para evitar decisões hoje, então esperei.",
        "Meu coração ficou travado no buffering pensando em você.",
        "Fui escrever pra você, mas me perdi nos seus olhos na foto do perfil.",
        "Meu celular sentiu ciúmes e apagou sua notificação.",
        "Estava treinando como te pedir em casamento e perdi a noção do tempo.",
        "Meu horóscopo disse para evitar decisões importantes, então esperei.",
        "Minha mãe começou a falar de casamento e precisei escapar.",
        "O universo conspirou contra nosso encontro hoje.",
        "Esqueci o que ia te dizer porque só penso em você.",
        "Meu gato deitou no meu celular e não me deixou pegar.",
        "Me distraí pensando em nós dois no futuro.",
        "O espelho me disse que eu precisava me arrumar melhor para te ver.",
        "Fui ensaiar um elogio e me emocionei demais.",
        "Meu Wi-Fi não quis me deixar falar com minha alma gêmea.",
        "Achei que era uma pegadinha do destino e hesitei antes de responder.",
        "O tempo parou quando vi sua mensagem, só que só pra mim.",
        "Estava escrevendo pra você, mas meu coração digitava mais rápido que meus dedos.",
        "O destino me pregou uma peça e perdi a hora do nosso encontro.",
        "Fiquei admirando sua última mensagem por tempo demais.",
        "O dia só começou de verdade quando vi sua mensagem.",
        "O universo quis testar nosso amor com um pequeno atraso.",
        "A Lua me distraiu enquanto pensava em você.",
        "Estava planejando uma surpresa e me enrolei.",
        "Meu espelho disse que eu precisava me arrumar melhor antes de falar com você.",
        "O elevador ficou preso enquanto eu ensaiava uma declaração.",
        "O vento levou meu celular quando fui responder sua mensagem.",
        "Fiquei sonhando acordado com a gente e esqueci da vida.",
        "Meu dedo escorregou e apaguei a resposta sem querer.",
        "O universo quis me deixar ansioso antes de te responder.",
        "Meu celular entrou no modo 'drama romântico' e travou.",
        "O Wi-Fi caiu só pra não deixar a gente se falar antes.",
        "Fui dar um print na sua mensagem fofa e acabei fechando o app.",
        "O relógio parou quando comecei a pensar em você.",
        "Meu coração acelerou tanto que precisei me recuperar antes de digitar.",
        "O amor nos coloca desafios, e hoje foi o atraso na resposta.",
        "Meu dedo congelou de nervoso ao tentar responder sua mensagem.",
        "Estava praticando minha melhor cantada e perdi o momento certo.",
        "O destino quis ver se nosso amor resiste a uns minutos de atraso.",
        "Estava planejando a mensagem perfeita e o tempo passou.",
        "Minha avó começou a contar histórias de amor e não consegui sair.",
        "Meu cachorro pegou o celular e quase te mandou um 'eu te amo' antes da hora.",
        "O espelho me mandou treinar minha cara de apaixonado antes de te responder.",
        "Fui tomar coragem pra te chamar e acabei dormindo sem querer.",
        "O tempo passou mais rápido enquanto eu pensava no nosso encontro.",
        "Fui anotar todas as coisas que gosto em você e perdi a hora.",
        "Meu gato esbarrou no celular e quase enviou um pedido de casamento.",
        "O universo estava em modo teste e bugou minha resposta.",
        "O trânsito parou e eu aproveitei pra planejar nosso futuro juntos.",
        "O café derramou e quase formou um coração na mesa.",
        "Me atrasei porque queria achar as palavras certas pra falar com você.",
        "Meu coração ficou offline por um momento de nervoso."
    ],
    trabalho: [
        "Meu despertador não tocou e acordei achando que era domingo.",
        "Meu gato derrubou café no meu teclado e tive que limpar tudo.",
        "A reunião foi adiada para o horário que eu já estava saindo.",
        "O despertador tocou, mas meu cérebro não aceitou o convite para acordar.",
        "Meu computador decidiu que hoje era dia de atualização infinita.",
        "O café da manhã virou uma missão impossível e atrasou tudo.",
        "O ônibus resolveu fazer um tour turístico antes de me levar pro trabalho.",
        "Meu chefe mandou um e-mail tão grande que precisei ler com calma antes de sair.",
        "Meu gato deitou no teclado e enviou um relatório incompleto.",
        "A impressora decidiu se rebelar e precisei convencê-la a funcionar.",
        "Meu relógio biológico decidiu que hoje era final de semana.",
        "O Wi-Fi da empresa caiu e passei a manhã tentando resolver.",
        "O elevador quebrou e precisei subir 15 andares de escada.",
        "Minha marmita vazou na mochila e precisei salvar meus documentos.",
        "O trânsito estava tão parado que pensei em abrir um escritório no carro.",
        "Meu chefe resolveu fazer uma reunião surpresa logo cedo.",
        "A chuva transformou meu caminho até o trabalho em um rio.",
        "Esqueci o crachá e tive que voltar pra casa pra pegar.",
        "Meu carro decidiu tirar um dia de folga sem avisar.",
        "O café estava tão forte que precisei me recuperar antes de trabalhar.",
        "O ar-condicionado estava tão frio que congelei por alguns minutos.",
        "Derrubei café no teclado e precisei esperar secar antes de trabalhar.",
        "O relógio parou e achei que ainda era madrugada.",
        "Minha agenda bugou e me lembrou do compromisso uma hora atrasado.",
        "Meu computador decidiu atualizar no pior momento possível.",
        "O despertador tocou, mas eu sonhei que já estava trabalhando.",
        "Tentei sair de casa, mas minha roupa de trabalho sumiu misteriosamente.",
        "Meu cachorro pegou minha meia e começou um jogo de pega-pega.",
        "Tentei responder um e-mail importante, mas o autocorretor me traiu.",
        "O telefone tocou e era um golpe, mas precisei ouvir tudo pra ter certeza.",
        "O metrô travou entre estações e precisei esperar o resgate.",
        "Derrubei o café na minha camisa e tive que trocar de roupa.",
        "Fui pegar um café e encontrei um colega que não parava de falar.",
        "A conta do café acabou e precisei ir comprar antes de funcionar direito.",
        "O site da empresa caiu e passei horas tentando resolver.",
        "Fiquei preso na reunião que deveria durar 5 minutos, mas durou 2 horas.",
        "Meu chefe resolveu filosofar sobre a vida no meio da nossa reunião.",
        "A máquina de café engoliu minhas moedas e precisei resgatá-las.",
        "Me perdi no caminho, mesmo indo pro mesmo lugar há anos.",
        "O teclado do computador parou de funcionar e precisei improvisar.",
        "O sistema caiu e fiquei esperando até poder trabalhar de novo.",
        "Fui imprimir um documento e a impressora decidiu mastigá-lo.",
        "A cadeira do escritório quebrou e precisei achar outra.",
        "Meu gato decidiu dormir em cima do meu notebook.",
        "Meu colega me chamou para um café e acabou virando um debate sobre o trabalho.",
        "O chefe pediu um relatório de última hora e precisei correr.",
        "O relógio da empresa estava adiantado e achei que estava atrasado.",
        "A internet ficou tão lenta que demorou uma hora pra abrir um e-mail.",
        "O elevador ficou preso entre andares e precisei esperar o resgate.",
        "Fui abrir um e-mail e sem querer mandei um 'bom dia' para toda a empresa.",
        "O fornecedor atrasou e precisei esperar antes de continuar meu trabalho.",
        "Me distraí organizando a mesa e quando vi, já estava atrasado.",
        "O computador deu tela azul no meio de um relatório importante."
    ],
    familia: [
        "Minha avó inventou que queria aprender a usar redes sociais e passei o dia ensinando.",
        "Tive que ajudar meu primo a montar um quebra-cabeça de 5000 peças.",
        "Minha tia resolveu contar histórias de família e não conseguia sair de lá.",
        "Minha avó resolveu contar histórias da juventude e não conseguia sair de lá.",
        "Meu primo pequeno escondeu minhas chaves e levou meia hora pra lembrar onde colocou.",
        "Tive que ajudar meu tio a configurar o celular novo.",
        "Minha mãe inventou de reorganizar a casa e precisei ajudar.",
        "Meu pai decidiu que hoje era o dia da faxina geral.",
        "Minha tia ligou e conversamos por 40 minutos sobre nada.",
        "Meu sobrinho apagou um arquivo importante e precisei recuperar.",
        "Tive que ir buscar meu irmão na escola porque ele esqueceu a mochila.",
        "O almoço de família se estendeu porque ninguém parava de falar.",
        "Minha avó pediu ajuda com o Facebook e passei horas ensinando.",
        "Meu cachorro fugiu e passei a manhã procurando ele com minha família.",
        "Minha prima quis aprender a cozinhar e incendiou metade da cozinha.",
        "Meu irmão travou o computador jogando e precisei formatar.",
        "Minha tia trouxe um bolo e precisei comer antes de sair.",
        "Meu avô perdeu os óculos e precisei ajudar a procurar.",
        "Minha mãe me trancou do lado de fora sem querer.",
        "Meu sobrinho derramou suco nos meus papéis e precisei reimprimir.",
        "Minha família resolveu discutir política bem na hora de eu sair.",
        "Fui acordado pelo meu pai dizendo que a gente tinha que resolver um 'problema urgente'.",
        "Minha irmã pegou minha roupa e precisei encontrar outra.",
        "Meu primo estava doente e precisei cuidar dele.",
        "O almoço atrasou porque meu avô decidiu contar piadas.",
        "Minha tia me mandou buscar algo no mercado de última hora.",
        "O carro da minha mãe quebrou e precisei ajudar.",
        "Tive que levar minha avó ao médico de emergência (era só uma unha encravada).",
        "Minha irmã derrubou o Wi-Fi e passei tempo tentando consertar.",
        "Meu pai trocou os móveis de lugar e fiquei preso no quarto.",
        "Meu sobrinho chorava tanto que precisei acalmá-lo antes de sair.",
        "Minha mãe inventou de limpar meu quarto bem quando eu ia sair.",
        "Meu avô me chamou pra ensinar como usar o WhatsApp.",
        "Meu cachorro comeu meu carregador e precisei achar outro antes de sair.",
        "Minha tia resolveu me visitar sem avisar e não parava de falar.",
        "Minha irmã pegou meu fone de ouvido e tive que procurar outro.",
        "Meu pai decidiu me ensinar algo que eu já sabia e fiquei ouvindo por educação.",
        "Minha prima se machucou brincando e precisei levar ela ao médico.",
        "Meu primo pequeno queria brincar e não me deixava sair.",
        "Minha mãe me pediu um favor de última hora.",
        "Minha avó queria que eu ajudasse a resolver palavras cruzadas.",
        "Meu cachorro engoliu algo estranho e precisei levar ao veterinário.",
        "Meu irmão esqueceu a senha do e-mail e precisei recuperar pra ele.",
        "Minha tia resolveu fazer um almoço especial e tive que comer antes de sair.",
        "Meu pai queria me mostrar como se troca um pneu, mesmo sem necessidade.",
        "Minha prima me ligou chorando por um motivo bobo e precisei consolá-la.",
        "Minha mãe pediu pra eu lavar a louça justo na hora que eu ia sair.",
        "Meu avô queria me ensinar a jogar dominó antes de eu sair.",
        "Meu irmão ficou preso no banheiro porque a fechadura quebrou.",
        "Minha mãe encontrou uma foto antiga e precisou contar a história dela.",
        "Meu cachorro fugiu pro quintal do vizinho e precisei buscar.",
        "Meu tio me chamou pra ver um vídeo e acabou me mostrando 30.",
        "Minha avó disse que eu não podia sair sem antes tomar um café."
    ],
    amigos: [
        "Meu amigo me chamou para um 'rolê rápido' e só acabou agora.",
        "Meu amigo esqueceu a carteira e tive que pagar o almoço dele.",
        "Meu amigo terminou o namoro e precisei consolá-lo.",
        "Meu amigo trancou as chaves dentro do carro e passei horas ajudando.",
        "Meu amigo quis testar um atalho e acabamos nos perdendo.",
        "Fui buscar meu amigo e o carro dele quebrou no caminho.",
        "Meu amigo decidiu cortar o cabelo sozinho e precisei consertar o estrago.",
        "Meu amigo apostou que eu não conseguiria comer um lanche gigante e precisei provar que ele estava errado.",
        "Fomos jogar videogame por meia horinha... durou 5 horas.",
        "Meu amigo esqueceu o celular na minha casa e tive que devolver.",
        "Meu amigo quis ver 'só mais um episódio' e agora já terminamos a série.",
        "Meu amigo pediu ajuda pra organizar uma festa surpresa.",
        "Meu amigo trancou a chave dentro de casa e precisei levá-lo pra pegar uma cópia.",
        "Meu amigo perdeu a carteira e fomos refazer todos os caminhos do dia.",
        "Fui dar carona para um amigo e o carro ficou sem gasolina.",
        "Meu amigo me desafiou a uma partida de sinuca e não podia recusar.",
        "Meu amigo fez um pedido gigante no drive-thru e demoramos uma eternidade.",
        "Meu amigo esqueceu onde estacionou o carro e passamos meia hora procurando.",
        "Meu amigo estava triste e precisava de alguém pra ouvir.",
        "Meu amigo quis fazer um churrasco improvisado e demorou muito pra acender o fogo.",
        "Fui ajudar meu amigo a se mudar e os móveis eram mais pesados do que imaginávamos.",
        "Meu amigo perdeu a chave de casa e precisei levá-lo para um chaveiro.",
        "Meu amigo quis 'só dar uma volta no shopping' e demoramos três horas.",
        "Meu amigo estava bêbado e precisei cuidar dele.",
        "Meu amigo insistiu que sabia um atalho e acabamos no fim do mundo.",
        "Meu amigo precisava de ajuda para escrever uma mensagem importante.",
        "Meu amigo esqueceu a senha do e-mail e precisei ajudá-lo a recuperar.",
        "Meu amigo quis cozinhar algo novo e quase explodiu a cozinha.",
        "Meu amigo achou que sabia consertar a pia e alagou a casa.",
        "Meu amigo quis jogar 'só mais uma partida' e jogamos a noite inteira.",
        "Meu amigo me ligou desesperado porque não sabia como usar uma planilha.",
        "Meu amigo comprou um móvel novo e precisava de ajuda pra montar.",
        "Meu amigo insistiu em ver um filme ruim só pra provar um ponto.",
        "Meu amigo quis 'só passar rapidinho' na casa de outra pessoa e demoramos uma eternidade.",
        "Meu amigo derrubou refrigerante no computador e precisei ajudá-lo a secar.",
        "Meu amigo se trancou no banheiro e precisei buscar ferramentas.",
        "Meu amigo insistiu que eu precisava conhecer um jogo novo e perdi o horário.",
        "Meu amigo pegou um caminho alternativo e ficamos presos no trânsito.",
        "Meu amigo queria cortar o cabelo e me levou junto para dar opinião.",
        "Meu amigo me chamou para resolver um problema técnico e levou a tarde inteira.",
        "Meu amigo quis 'só dar uma olhadinha' numa loja e comprou meia loja.",
        "Meu amigo estava atrasado e precisei esperá-lo.",
        "Meu amigo teve um encontro ruim e precisou desabafar.",
        "Meu amigo decidiu consertar o carro sozinho e quase desmontou o motor.",
        "Meu amigo ficou sem bateria e precisei emprestar o celular.",
        "Meu amigo me chamou para ver 'uma coisa rápida' e fiquei preso na conversa.",
        "Meu amigo perdeu o ingresso do evento e tivemos que procurar.",
        "Meu amigo me ligou pedindo carona de última hora.",
        "Meu amigo quis ensinar um truque de skate e acabou se machucando.",
        "Meu amigo achou que sabia estacionar e ficamos meia hora tentando sair do lugar."
    ],
    classicas: [
        "Fiquei sem sinal.",
        "Meu celular descarregou.",
        "Eu não vi a mensagem.",
        "Peguei trânsito.",
        "Tive um imprevisto de última hora.",
        "Esqueci completamente!",
        "Achei que era amanhã.",
        "Meu despertador não tocou.",
        "Estava passando mal.",
        "Deu um problema aqui em casa.",
        "Meu cachorro comeu minha tarefa.",
        "Eu estava resolvendo umas coisas importantes.",
        "Perdi a noção do tempo.",
        "Meu computador travou bem na hora.",
        "Tive que ajudar um amigo.",
        "Precisei ficar no trabalho até mais tarde.",
        "O ônibus demorou demais.",
        "Peguei o caminho errado e me atrasei.",
        "Esqueci que tinha combinado isso.",
        "Fui pegar algo rapidinho e acabou demorando.",
        "Meu chefe me prendeu em uma reunião.",
        "Meu carro quebrou.",
        "Bati o dedinho e precisei me recuperar.",
        "Tive um compromisso de última hora.",
        "Fiquei sem internet.",
        "Deu um apagão aqui em casa.",
        "Meu celular caiu na água e parou de funcionar.",
        "Fiquei sem bateria e sem carregador.",
        "Meu irmão ocupou o computador a tarde toda.",
        "Meu gato derrubou um copo d’água no meu teclado.",
        "Peguei um engarrafamento infernal.",
        "Esqueci a senha do sistema e não conseguia acessar.",
        "Achei que era só semana que vem.",
        "Meu primo pegou meu celular e não vi as mensagens.",
        "Estava muito ocupado.",
        "Fui ajudar minha mãe com uma coisa urgente.",
        "Deu um problema na minha conta e precisei resolver.",
        "Meu relógio estava errado.",
        "Alguém me confundiu e passei horas resolvendo.",
        "Achei que já tinha respondido.",
        "Precisei sair correndo e não deu tempo.",
        "Tive que levar minha avó ao médico.",
        "O despertador tocou, mas eu apaguei sem querer.",
        "Meu telefone ficou no silencioso.",
        "Fui só tirar um cochilo e acordei agora.",
        "Esqueci de configurar o alarme.",
        "Tive que buscar alguém no aeroporto.",
        "O elevador do prédio quebrou e tive que subir de escada.",
        "Peguei um número errado e só percebi depois.",
        "Fui mexer em alguma coisa e quebrei sem querer."
    ],
    televisivas: [
        //animes
        "Fui assistir um episódio de uma série e acabei maratonando a temporada inteira.",
        "Meu amigo me chamou pra ver um filme e não consegui sair.",
        "Estava assistindo um anime e perdi a noção do tempo.",
        "Fui ao cinema e acabei perdendo a noção do tempo.",
        "Meu amigo me convenceu a assistir um filme e só percebi agora.",
        "Estava tão envolvido na trama que não consegui parar.",
        "Fui assistir um episódio de uma série e acabei maratonando a temporada inteira.",
        "Meu amigo me chamou pra ver um filme e não consegui sair.",
        "Estava assistindo um anime e perdi a noção do tempo.",
        "Fui ao cinema e acabei perdendo a noção do tempo.",
        "Meu amigo me convenceu a assistir um filme e só percebi agora.",
        "Fui treinar na Sala do Tempo e me perdi no espaço-tempo. (Dragon Ball)",
        "Meu shinigami me distraiu e perdi a hora. (Death Note)",
        "Tive que enfrentar um Titã e acabei atrasando. (Attack on Titan)",
        "Precisei resolver um problema na Associação dos Caçadores. (Hunter x Hunter)",
        "Meu sharingan previu que não daria certo sair hoje. (Naruto)",
        "Estava treinando meu Haki e perdi a noção do tempo. (One Piece)",
        "Um hollow apareceu bem na minha frente e tive que lidar com isso. (Bleach)",
        "Precisei correr da Equipe Rocket antes que me sequestrassem. (Pokémon)",
        "Fui pego no Genjutsu e só acordei agora. (Naruto)",
        "Tive que capturar um novo Stand do nada. (JoJo's Bizarre Adventure)",
        "Estava resolvendo um problema de alquimia e acabei preso em outra dimensão. (Fullmetal Alchemist)",
        "Fui desafiado para um duelo de cartas e não pude recusar. (Yu-Gi-Oh!)",
        "Meu Death Note caiu no chão e tive que procurar. (Death Note)",
        "Estava em um torneio de luta mortal, desculpa o atraso. (Dragon Ball)",
        "Precisei correr atrás de um Digimon que fugiu. (Digimon)",
        "Uma bruxa me amaldiçoou e precisei resolver isso antes de sair. (Re:Zero)",
        "Meu Eva travou e precisei reconfigurar. (Neon Genesis Evangelion)",
        "Fiquei perdido no mundo dos espíritos. (Spirited Away)",
        "Meu nome foi escrito no caderno errado, então precisei negociar minha vida. (Death Note)",
        "Estava aprendendo alquimia e acabei virando metade metal. (Fullmetal Alchemist)",
        "Peguei um trem para a Vila Oculta da Folha por engano. (Naruto)",
        "Um mago me teleportou para outro mundo sem querer. (Konosuba)",
        "O Kira quase me pegou, precisei sumir por um tempo. (Death Note)",
        "Fui desafiado para um shokugeki e não podia recusar. (Shokugeki no Soma)",
        "Precisei aprender uma nova respiração para enfrentar um Oni. (Demon Slayer)",
        "Minha pokébola quebrou e meu Pikachu fugiu. (Pokémon)",
        "Me perdi no labirinto de Aincrad. (Sword Art Online)",
        "Fui transportado para um isekai e só consegui voltar agora. (Qualquer isekai)",
        "Precisei ajudar um robô gigante em uma batalha. (Gundam)",
        "Meu grimório sumiu e passei horas procurando. (Black Clover)",
        "O relógio Omnitrix não queria me transformar e fiquei preso na luta. (Ben 10, mas parece anime)",
        "A Akatsuki me caçou e tive que me esconder. (Naruto)",
        "Um Death Gun tentou me matar e precisei fugir. (Sword Art Online)",
        "Precisei derrotar um yokai antes de continuar meu dia. (Natsume Yuujinchou)",
        "O All Might me deu um treinamento especial e não podia faltar. (My Hero Academia)",
        "Precisei recuperar as esferas do dragão para um desejo urgente. (Dragon Ball)",
        "A Mikasa me sequestrou para me proteger de titãs. (Attack on Titan)",
        "Estava criando uma nova armadura sagrada. (Cavaleiros do Zodíaco)",
        "Passei o dia tentando cozinhar algo com energia espiritual. (Jujutsu Kaisen)",
        "Precisei investigar um mistério sobrenatural na minha escola. (Hyouka)",
        "Um demônio tentou fazer um contrato comigo e demorou para recusar. (Black Butler)",
        "Fui escolhido para lutar na Guerra do Santo Graal. (Fate series)",
        "Meu mecha ficou sem combustível e precisei reabastecer. (Evangelion / Code Geass)",
        "Um alquimista maluco me transformou num homúnculo por acidente. (Fullmetal Alchemist)",
        "Meu sensei me colocou para treinar até o limite. (Naruto)",
        "A Homura tentou resetar a linha do tempo de novo. (Madoka Magica)",
        "Fiquei preso no tempo infinito do Tsukuyomi. (Naruto)",
        "Uma carta Clow me causou problemas o dia todo. (Cardcaptor Sakura)",
        "Precisei salvar minha vila com um novo jutsu secreto. (Naruto)",
        "Meu stand resolveu agir sozinho e causou o maior caos. (JoJo’s Bizarre Adventure)",
        "O L me chamou para ajudá-lo em um caso, então fiquei ocupado. (Death Note)",
        "Me desafiaram para uma corrida de drift no Monte Akina. (Initial D)",
        "Minha guilda me convocou para uma missão urgente. (Fairy Tail)",
        "Precisei selar um espírito maligno que apareceu do nada. (Jujutsu Kaisen)",
        "Uma bruxa do caos bagunçou minha linha do tempo. (Re:Zero)",
        "Meu Gundam quebrou no meio da batalha e tive que consertar. (Mobile Suit Gundam)",
        "Estava enfrentando um Hollow que invadiu minha cidade. (Bleach)",
        "O Exército Revolucionário me recrutou à força. (One Piece)",
        "O King Bradley me perseguiu e precisei fugir. (Fullmetal Alchemist)",
        "Meu pai vendeu minha alma para um demônio, então tive que negociar. (Black Butler)",
        "O Exame Hunter demorou mais do que eu esperava. (Hunter x Hunter)",
        "A Saber me chamou para um duelo e não pude recusar. (Fate Series)",
        "Meu shikigami fugiu e precisei buscá-lo. (Noragami)",
        "Um Ghouls tentou me devorar e tive que me defender. (Tokyo Ghoul)",
        "Fui arrastado para o Torneio das Trevas sem querer. (Yu Yu Hakusho)",
        "O Dio congelou o tempo e só voltei agora. (JoJo's Bizarre Adventure)",
        "Fiquei preso em um jogo sem botão de logout. (Sword Art Online)",
        "Meu death flag foi ativado e precisei evitá-lo. (Qualquer isekai)",
        "O Goku me chamou para um treino de 100x a gravidade da Terra. (Dragon Ball)",
        "Meu Grimório abriu sozinho e comecei a flutuar. (Black Clover)",
        "Peguei carona no Trem do Infinito e acabei perdido. (Demon Slayer)",
        "Estava no meio de uma dança de exorcismo. (Jujutsu Kaisen)",
        "O Itachi me colocou em um genjutsu eterno e só acordei agora. (Naruto)",
        "Tive que enfrentar meu próprio clone maligno. (Qualquer anime shonen)",
        "Meu poder despertou sozinho e desmaiei de exaustão. (Bleach)",
        "O Asta me convenceu a treinar sem magia e desmaiei no meio. (Black Clover)",
        "Me perdi no labirinto da Dungeon errada. (DanMachi)",
        "Um vampiro tentou me transformar e precisei fugir. (Hellsing)",
        "Tive que fugir de um contrato suspeito com um demônio. (Chainsaw Man)",
        "Meu espírito guerreiro foi convocado e não pude recusar. (Shaman King)",
        "Um demônio devorador de sonhos me capturou e só escapei agora. (Demon Slayer)",
        "O Zenitsu me ensinou um golpe novo, mas dormi no processo. (Demon Slayer)",
        "Minha nota de matemática estava ruim e precisei virar um gênio do nada. (Dr. Stone)",
        "Fiquei tempo demais treinando minha nova técnica secreta. (Naruto)",
        "Fui escolhido como próximo Hokage e precisei resolver uns assuntos. (Naruto)",
        "Me obrigaram a estudar para entrar na U.A. (My Hero Academia)",
        "Um vilão explodiu minha casa e precisei reconstruir. (One Punch Man)",
        "O Sukuna assumiu o controle do meu corpo e causou confusão. (Jujutsu Kaisen)",
        "Meu cavaleiro de ouro favorito me chamou para um treino. (Cavaleiros do Zodíaco)",
        "O Gilgamesh apareceu e tentou me matar do nada. (Fate Series)",
        "Me perdi no mundo das cartas de duelo. (Yu-Gi-Oh!)",
        "Um feitiço de tempo me prendeu num loop infinito. (Steins;Gate)",
        "A Nami pegou todo o meu dinheiro e precisei trabalhar para recuperar. (One Piece)",
        "A Kurisu começou a falar sobre física quântica e perdi a noção do tempo. (Steins;Gate)",
        "Fiquei refletindo sobre a tristeza da vida e da humanidade. (Neon Genesis Evangelion)",
        "Meu código foi hackeado e precisei entrar no digital para resolver. (Digimon)",
        "Precisei aprender a controlar minha aura antes de sair de casa. (Hunter x Hunter)",
        "Me convocaram para um jogo mortal onde só um sobrevive. (Darwin’s Game)",
        "Minha espada mágica se quebrou e precisei forjar outra. (Qualquer anime de fantasia)",
        "O Koro-sensei me deu um dever de casa impossível e passei o dia todo tentando resolver. (Assassination Classroom)",
        //filmes
        "Fui assistir um filme e acabei maratonando a trilogia inteira.",
        "Fiquei preso em um loop temporal e só consegui sair agora. (Feitiço do Tempo)",
        "Tive que salvar o mundo de um apocalipse iminente. (Armageddon)",
        "Um DeLorean me levou para o passado sem querer. (De Volta Para o Futuro)",
        "O Thanos estalou os dedos e só voltei agora. (Vingadores: Ultimato)",
        "Tive que resgatar minha filha no sonho dela. (A Origem)",
        "Fui convocado para caçar fantasmas na cidade. (Os Caça-Fantasmas)",
        "Estava em uma missão secreta para o governo. (Missão: Impossível)",
        "Um tubarão gigante apareceu e precisei fugir. (Tubarão)",
        "Fiquei preso em um parque com dinossauros soltos. (Jurassic Park)",
        "Meu carro foi roubado pelo John Wick e tive que resolver. (John Wick)",
        "O Rambo me chamou para uma guerra inesperada. (Rambo)",
        "Minha identidade secreta quase foi revelada. (Homem-Aranha)",
        "Tive que treinar para um torneio mortal. (Mortal Kombat)",
        "Meu avião caiu em uma ilha deserta. (O Náufrago)",
        "Estava sendo perseguido por um assassino mascarado. (Pânico)",
        "Um androide veio do futuro tentar me eliminar. (O Exterminador do Futuro)",
        "Precisei escapar de um jogo mortal. (Jogos Vorazes)",
        "Fui escolhido para pilotar um robô gigante contra monstros. (Círculo de Fogo)",
        "Fiquei preso dentro de uma realidade virtual. (Matrix)",
        "Um palhaço assustador apareceu na minha cidade. (It: A Coisa)",
        "Fui convocado para um assalto épico. (La Casa de Papel – Filme futuramente?)",
        "Fui atacado por um boneco assassino. (Brinquedo Assassino)",
        "Uma múmia amaldiçoada me perseguiu. (A Múmia)",
        "Fiquei perdido em um planeta desconhecido. (Perdido em Marte)",
        "Precisei proteger um anel mágico de um vilão sombrio. (O Senhor dos Anéis)",
        "Meu clone tentou tomar meu lugar. (O Sexto Dia)",
        "Precisei aprender kung fu em tempo recorde. (Karatê Kid)",
        "Uma inteligência artificial tentou me controlar. (Her)",
        "Meu hotel era assombrado e não consegui sair. (O Iluminado)",
        "Tive que impedir uma invasão alienígena. (Dia da Independência)",
        "Me perdi no espaço e só agora consegui voltar. (Gravidade)",
        "Um monstro gigante destruiu minha cidade. (Godzilla)",
        "Vi um assassino indestrutível me perseguindo. (Halloween)",
        "Fui sequestrado por piratas espaciais. (Guardiões da Galáxia)",
        "Fui desafiado para um duelo de pistolas no Velho Oeste. (Três Homens em Conflito)",
        "Precisei ajudar um robô a salvar a humanidade. (Wall-E)",
        "Passei um tempo no fundo do mar estudando uma cidade perdida. (Aquaman)",
        "Estava preso dentro de um jogo de tabuleiro. (Jumanji)",
        "Fiquei preso em uma fábrica de chocolate bizarra. (A Fantástica Fábrica de Chocolate)",
        "O Pennywise me chamou para uma conversa e eu não consegui escapar. (It: A Coisa)",
        "Precisei enfrentar um mago maligno que queria dominar o mundo. (Harry Potter)",
        "Fui convidado para um jantar estranho onde todos começaram a desaparecer. (Entre Facas e Segredos)",
        "Encontrei uma lâmpada mágica e perdi tempo fazendo pedidos. (Aladdin)",
        "Fui engolido por um buraco negro e só consegui escapar agora. (Interestelar)",
        "Precisei recuperar um artefato roubado antes que causasse o fim do mundo. (Indiana Jones)",
        "Fiquei em um trem cheio de zumbis e precisei sobreviver. (Invasão Zumbi)",
        "Me transformei em um super-herói do nada e não soube o que fazer. (Shazam!)",
        "Meu carro se tornou um robô e me levou para uma batalha intergaláctica. (Transformers)",
        "Passei meses treinando para um campeonato de boxe. (Rocky)",
        "Meu brinquedo favorito começou a falar sozinho e entrei em pânico. (Toy Story)",
        "Estava ajudando o Batman a salvar Gotham. (O Cavaleiro das Trevas)",
        "Fui escolhido como o novo Pantera Negra e tive que treinar. (Pantera Negra)",
        "O Homem de Ferro me recrutou para uma missão secreta. (Homem de Ferro)",
        "Um DeLorean bugado me mandou para a Idade Média. (De Volta Para o Futuro III)",
        "Encontrei uma mala cheia de dinheiro e precisei fugir. (Onde os Fracos Não Têm Vez)",
        "Fiquei preso dentro de um sonho dentro de um sonho. (A Origem)",
        "Me escondi de um assassino silencioso que só mata no escuro. (Um Lugar Silencioso)",
        "Fui desafiado para um duelo de varinhas mágicas. (Harry Potter)",
        "Tive que impedir que um brinquedo do mal tomasse controle da minha casa. (M3GAN)",
        "Passei o dia resolvendo enigmas para escapar de um jogo mortal. (Jogos Mortais)",
        "Um grupo de palhaços alienígenas invadiu minha cidade. (Palhaços Assassinos do Espaço Sideral)",
        "Meu carro decidiu ter vida própria e me sequestrou. (Christine, o Carro Assassino)",
        "Passei a noite tentando escapar de uma casa mal-assombrada. (Invocação do Mal)",
        "Me perdi no mundo digital e só consegui sair agora. (Tron)",
        "Fui sugado para dentro de um jogo de tabuleiro. (Jumanji)",
        "Precisei ajudar uma família a fugir de um parque de dinossauros. (Jurassic World)",
        "Meu anel mágico me teleportou para outra dimensão. (O Senhor dos Anéis)",
        "Descobri que sou um mutante e passei o dia testando meus poderes. (X-Men)",
        "Um assassino mascarado tentou me caçar a noite inteira. (Sexta-Feira 13)",
        "Passei horas dentro de um labirinto com criaturas bizarras. (Labirinto - A Magia do Tempo)",
        "Meu avião caiu no Triângulo das Bermudas e só voltei agora. (Perdidos no Espaço)",
        "Um robô assassino começou a me perseguir. (O Exterminador do Futuro)",
        "Descobri que minha vida inteira era um reality show. (O Show de Truman)",
        "Fui escolhido como o próximo gladiador. (Gladiador)",
        "Fui transportado para o mundo dos piratas. (Piratas do Caribe)",
        "Precisei atravessar um deserto pós-apocalíptico para sobreviver. (Mad Max)",
        "Tive que ajudar um detetive a resolver um mistério bizarro. (Sherlock Holmes)",
        "Passei a noite fugindo de zumbis famintos. (Resident Evil)",
        "Fui desafiado para um duelo intergaláctico de sabres de luz. (Star Wars)",
        "Estava testando minha nova armadura tecnológica e perdi a noção do tempo. (Homem de Ferro)",
        "Um grupo de ninjas me atacou e precisei me defender. (Kill Bill)",
        "Me transformei em um vampiro e passei a noite fugindo de caçadores. (Drácula de Bram Stoker)",
        "Me perdi no espaço e fui resgatado por um grupo de alienígenas. (Guardiões da Galáxia)",
        "Encontrei um livro mágico e sem querer liberei um monstro. (A Múmia)",
        "Fui escolhido como o próximo rei da selva e precisei aprender a governar. (O Rei Leão)",
        "Um vilão sequestrou minha princesa e precisei salvá-la. (Shrek)",
        "Entrei no trem para Hogwarts por engano. (Harry Potter)",
        "Um monstro do pântano invadiu minha casa e precisei lutar. (O Monstro do Pântano)",
        "Passei o dia inteiro fugindo de um caçador intergaláctico. (Predador)",
        "Um meteoro estava vindo em direção à Terra e precisei impedir. (Impacto Profundo)",
        "Entrei em um bar misterioso e descobri que todos lá eram vampiros. (Um Drink no Inferno)",
        "Um supervilão tentou me hipnotizar e levei horas para me livrar. (Megamente)",
        "Fui desafiado para uma luta de kung fu e precisei treinar. (O Grande Dragão Branco)",
        "Meu GPS me levou para dentro de uma dimensão paralela. (Interestelar)",
        "Precisei correr para entregar um anel antes que o mal tomasse conta. (O Senhor dos Anéis)",
        "Meu mentor desapareceu e precisei seguir as pistas dele. (Indiana Jones)",
        "Um espelho mágico me transportou para outro mundo. (Alice no País das Maravilhas)",
        "Fui desafiado para um torneio de batalhas interdimensionais. (Mortal Kombat)",
        "Um monstro gigante atacou minha cidade e precisei me esconder. (Cloverfield)",
        "Me tornei um espião sem querer e precisei completar uma missão secreta. (Kingsman)",
        "Fui transportado para o mundo dos sonhos e só consegui voltar agora. (A Origem)",
        "Um espírito maligno me perseguiu o dia todo. (Atividade Paranormal)",
        "Fui desafiado para uma batalha de dança intergaláctica. (Guardiões da Galáxia)",
        "Fiquei preso em um jogo de tabuleiro mágico. (Jumanji)",
        //series
        "Fui assistir um episódio de uma série e acabei maratonando a temporada inteira.",
        "Meu amigo me chamou pra ver um filme e não consegui sair.",
        "Estava assistindo um anime e perdi a noção do tempo.",
        "Fui ao cinema e acabei perdendo a noção do tempo.",
        "Meu amigo me convenceu a assistir um filme e só percebi agora.",
        "Estava tão envolvido na trama que não consegui parar.",
        "Fui assistir um episódio de uma série e acabei maratonando a temporada inteira.",
        "Meu amigo me chamou pra ver um filme e não consegui sair.",
        "Estava assistindo um anime e perdi a noção do tempo.",
        "Fui ao cinema e acabei perdendo a noção do tempo.",
        "Meu amigo me convenceu a assistir um filme e só percebi agora.",
        "Estava assistindo uma série incrível e perdi a noção do tempo.",
        "Meu amigo me chamou pra ver 'só mais um episódio' e acabei maratonando a temporada inteira.",
        "Estava tão envolvido na trama que não consegui parar.",
        "Fui assistir 'só mais um episódio' e acabei maratonando a temporada inteira.",
        "Meu amigo me chamou pra ver 'só mais um episódio' e acabei maratonando a temporada inteira.",
        "Precisei ajudar o Sherlock a resolver um caso. (Sherlock)",
        "O Walter White me chamou para um 'negócio urgente'. (Breaking Bad)",
        "Fiquei preso no Upside Down. (Stranger Things)",
        "Estava ocupado defendendo Westeros. (Game of Thrones)",
        "Fui abduzido pelos alienígenas do Arquivo X. (The X-Files)",
        "Meu amigo virou um zumbi e precisei cuidar dele. (The Walking Dead)",
        "Estava investigando um crime na BAU. (Criminal Minds)",
        "Precisei cobrir um escândalo da Casa Branca. (Scandal)",
        "Tive que impedir um assassinato antes que ele acontecesse. (Person of Interest)",
        "Meu loop temporal bugou e só consegui sair agora. (Dark)",
        "Fui chamado para um assalto na Casa da Moeda. (La Casa de Papel)",
        "Estava ajudando o Dexter a esconder um corpo. (Dexter)",
        "Fui interrogado pela SVU. (Law & Order: SVU)",
        "Meu amigo sumiu e precisei encontrá-lo. (Supernatural)",
        "Estava no espaço tentando salvar a Terra. (The Expanse)",
        "Minha inteligência artificial travou e precisei consertá-la. (Westworld)",
        "Fui sequestrado pelo Demolidor e só me soltaram agora. (Daredevil)",
        "Me perdi no labirinto da mente do Legion. (Legion)",
        "Estava tentando impedir uma invasão alienígena. (Doctor Who)",
        "Meu vizinho é um serial killer e precisei fugir. (You)",
        "Um velho disse que sou o Escolhido e fui treinar. (The Witcher)",
        "Tive que fingir ser um advogado brilhante sem diploma. (Suits)",
        "Meu amigo é um robô e precisei ajudá-lo a se esconder. (Black Mirror)",
        "Descobri que sou um clone e fui atrás da verdade. (Orphan Black)",
        "Precisei caçar vampiros e demônios a noite toda. (Buffy, a Caça-Vampiros)",
        "Fiz um pacto com um diabo charmoso e precisei cumprir. (Lucifer)",
        "Estava fugindo da polícia porque sou um hacker procurado. (Mr. Robot)",
        "Me teleportei para um mundo medieval por acidente. (The Last Kingdom)",
        "Meu chefe era um psicopata e precisei sumir. (The Office)",
        "Fui escolhido como um tributo e tive que lutar. (The 100)",
        "Um monstro saiu de um portal e precisei lutar com ele. (The Witcher)",
        "Descobri que meu melhor amigo é um espião. (Alias)",
        "Passei o dia tentando descobrir um mistério na cidade. (Twin Peaks)",
        "Fui convocado para um julgamento galáctico. (The Mandalorian)",
        "Meu computador começou a falar comigo e precisei resolver isso. (Person of Interest)",
        "Minha família é uma bagunça e precisei resolver tretas. (This Is Us)",
        "Me tornei presidente sem querer e precisei governar. (House of Cards)",
        "Estava perdido no tempo tentando consertar a linha temporal. (Loki)",
        "Me transformei em um vampiro e precisei me esconder. (What We Do in the Shadows)",
        "Descobri que sou um bruxo e tive que aprender feitiços. (Charmed)",
        "Precisei lutar contra monstros para salvar minha cidade. (Teen Wolf)",
        "Me tornei um ciborgue por acidente e precisei me adaptar. (Love, Death & Robots)",
        "Estava dentro de um videogame e tive que zerá-lo para sair. (Sword Art Online)",
        "Um assassino mascarado começou a me perseguir. (Scream: The TV Series)",
        "Fui preso injustamente e precisei bolar um plano de fuga. (Prison Break)",
        "Meu mundo virou de cabeça para baixo e precisei entender o porquê. (The OA)",
        "Descobri que minha cidade tem um grupo de vigilantes secretos. (Arrow)",
        "Fui chamado para uma missão intergaláctica e só voltei agora. (Star Trek)",
        "Me tornei um lobisomem e tive que aprender a me controlar. (The Originals)",
        "Um assassino com um caderno misterioso estava atrás de mim. (Death Note)",
        "Passei o dia tentando resolver um caso com o Monk. (Monk)",
        "Minha casa foi assombrada e precisei chamar os Winchester. (Supernatural)",
        "O FBI me colocou no Programa de Proteção a Testemunhas. (The Blacklist)",
        "Me juntei aos Peaky Blinders e a gangue me manteve ocupado. (Peaky Blinders)",
        "Descobri que sou um dos clones do Projeto Leda. (Orphan Black)",
        "Fiquei preso na prisão de Litchfield. (Orange Is the New Black)",
        "Minha mãe sumiu e tive que procurar pistas. (Pretty Little Liars)",
        "Precisei ajudar a resolver um assassinato em Neptune. (Veronica Mars)",
        "Estava em um reality show onde só um pode sobreviver. (Squid Game)",
        "Me tornei um fantasma e precisei aprender a assombrar. (Ghosts)",
        "A Umbrella Academy me chamou para salvar o mundo. (The Umbrella Academy)",
        "Meu chefe é um assassino, então não pude sair mais cedo. (Dexter)",
        "Uma bruxa jogou uma maldição em mim. (Once Upon a Time)",
        "Estava em um bar bebendo com os filhos de Ragnar. (Vikings)",
        "O Tony Soprano me chamou para uma 'reunião de negócios'. (The Sopranos)",
        "O professor Xavier me convocou para uma missão. (X-Men: The Animated Series)",
        "Me perdi na ilha e precisei sobreviver. (Lost)",
        "Fiquei preso dentro da The Good Place. (The Good Place)",
        "O Ted Mosby começou a contar outra história e perdi a noção do tempo. (How I Met Your Mother)",
        "Tive que fugir de um parque cheio de dinossauros. (Terra Nova)",
        "Me infiltrei no cartel e agora estou fugindo. (Narcos)",
        "Entrei no Yellowjackets e agora sou parte de um culto. (Yellowjackets)",
        "Passei o dia tentando escapar de uma realidade alternativa. (Fringe)",
        "Fiquei viciado em café e resolvendo mistérios. (Gilmore Girls)",
        "Me transformei em uma marionete do Jigsaw. (Saw: The Series)",
        "Tentei fugir do subúrbio perfeito, mas sempre voltava. (Wayward Pines)",
        "Passei anos congelado e acordei sem saber onde estava. (Altered Carbon)",
        "Alguém hackeou minha vida e precisei consertar tudo. (Black Mirror)",
        "Estava preso no bunker do apocalipse e só agora saí. (Unbreakable Kimmy Schmidt)",
        "Precisei ajudar os vampiros a se adaptarem ao século XXI. (What We Do in the Shadows)",
        "Fui parar na Idade Média e tive que aprender a sobreviver. (Merlin)",
        "Descobri que sou um ciborgue e agora estou tentando entender minha nova vida. (Love, Death & Robots)",
        "Passei o dia fugindo de uma distopia controlada por um governo opressor. (The Handmaid’s Tale)",
        "Estava aprendendo a caçar monstros com Geralt de Rívia. (The Witcher)",
        "Fui convidado para o casamento vermelho. (Game of Thrones)",
        "O Dr. House me diagnosticou com algo raro e precisei ficar em observação. (House M.D.)",
        "Meu advogado é o Saul Goodman e ele disse para eu sumir por um tempo. (Better Call Saul)",
        "Fui levado para um orfanato cheio de mistérios. (The Haunting of Hill House)",
        "Me tornei um cavaleiro Jedi e precisei lutar contra o Império. (The Mandalorian)",
        "Meu escritório entrou em guerra por uma máquina de café. (The Office)",
        "Precisei fugir de um casamento arranjado pelo rei. (Reign)",
        "Fui sugado para dentro de um jogo de RPG e tive que encontrar uma saída. (Critical Role)",
        "Me tornei um lobisomem e precisei aprender a me controlar. (Teen Wolf)",
        "Descobri que minha casa é uma prisão subterrânea. (The Wilds)",
        "O Mr. Robot me deu uma missão e não pude recusar. (Mr. Robot)",
        "Passei a noite enfrentando palhaços assassinos em um parque de diversões. (American Horror Story)",
        "Fui convidado para um jantar bizarro na mansão de um milionário. (The White Lotus)",
        "Um milhão de versões minhas começaram a aparecer no multiverso. (Rick and Morty)",
        "Entrei para um clube secreto de luta onde ninguém fala sobre isso. (Fight Club... mas na TV)",
        "O Batman me pediu ajuda, e quem sou eu para negar? (Gotham)"
    ]
};

function startChat() {
    addMessage("Digite a categoria: absurdas, classicas, aleatorias ou tematicas", "bot-message", "Bot i'm sorry");
}

function processInput() {
    let userInput = document.getElementById("userInput").value.toLowerCase().trim();
    if (excuses[userInput]) {
        addMessage(`Você escolheu: ${userInput}`, "user-message", "You");
        generateExcuse(userInput);
    } else if (userInput === "tematicas") {
        addMessage("Escolha um tema: televisivas, namoro, amigos, trabalho ou familia", "bot-message", "Bot lo lamento");
    } else if (["namoro", "televisivas", "amigos", "trabalho", "familia"].includes(userInput)) {
        addMessage(`Você escolheu: ${userInput}`, "user-message", "You");
        generateExcuse(userInput);
    } else {
        addMessage("Categoria não encontrada! Tente: absurdas, aleatorias ou tematicas", "bot-message", "Bot ごめんなさい");
    }
    document.getElementById("userInput").value = "";
}

function generateExcuse(category) {
    let excuse = excuses[category][Math.floor(Math.random() * excuses[category].length)];
    addMessage(excuse, "bot-message", "Bot desculpe");
}

function addMessage(text, className, name) {
    let chatBox = document.getElementById("chatBox");
    let message = document.createElement("div");
    message.classList.add("message", className);

    let nameTag = document.createElement("div");
    nameTag.classList.add("name");
    nameTag.innerText = name;

    let textNode = document.createElement("div");
    textNode.innerText = text;

    message.appendChild(nameTag);
    message.appendChild(textNode);

    chatBox.appendChild(message);
    chatBox.scrollTop = chatBox.scrollHeight;
}

window.onload = startChat;